services:
    app:
        build:
            context: .
            target: production
        environment:
            - NODE_ENV=production
            - DEBUG=app:*
            - PORT=1234
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app
        command: npm run start:prod
        depends_on:
            - postgres
        networks:
            - internal
            - data

    caddy:
        image: caddy:2
        ports:
            - "1234:80"
            - "1235:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - public
            - internal

    postgres:
        image: postgres:16
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=app
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - data

volumes:
    caddy_data:
    caddy_config:
    postgres_data:

networks:
    internal:
    data:
    public:
        driver: bridge
